// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SiteConstructor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Entities.LocalUser.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Entities.UserSiteData.UserSiteData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackgroundColorsId")
                        .HasColumnType("int");

                    b.Property<string>("ColorSchemeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadersFont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoBackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTextFont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RemoveLogoBackground")
                        .HasColumnType("bit");

                    b.Property<string>("TelegramLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TextColorsId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VkLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundColorsId");

                    b.HasIndex("TextColorsId");

                    b.ToTable("UsersSiteData", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ValueObjects.SiteData.BackgroundColors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Main")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navigation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translucent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BackgroundColors", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ValueObjects.SiteData.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFileBase64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserSiteDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserSiteDataId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ValueObjects.SiteData.TextColors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Additional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Main")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translucent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TextColors", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Entities.UserSiteData.UserSiteData", b =>
                {
                    b.HasOne("Domain.Models.ValueObjects.SiteData.BackgroundColors", "BackgroundColors")
                        .WithMany()
                        .HasForeignKey("BackgroundColorsId");

                    b.HasOne("Domain.Models.ValueObjects.SiteData.TextColors", "TextColors")
                        .WithMany()
                        .HasForeignKey("TextColorsId");

                    b.Navigation("BackgroundColors");

                    b.Navigation("TextColors");
                });

            modelBuilder.Entity("Domain.Models.ValueObjects.SiteData.Image", b =>
                {
                    b.HasOne("Domain.Models.Entities.UserSiteData.UserSiteData", "UserSiteData")
                        .WithMany("Images")
                        .HasForeignKey("UserSiteDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSiteData");
                });

            modelBuilder.Entity("Domain.Models.Entities.UserSiteData.UserSiteData", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
